use std::{borrow::Cow, collections::BTreeSet, fmt::Write};

use heck::{ToLowerCamelCase, ToSnakeCase};
use specta::{
    Types,
    datatype::{DataType, NamedReferenceType, Reference},
};
use specta_serde::{Phase, PhasesFormat, select_phase_datatype};
use specta_typescript::{Error, Exporter, FrameworkExporter, Typescript, primitives};

use crate::{Command, EventSchema};

pub(crate) fn generate(
    types: &Types,
    commands: &[Command],
    events: &[EventSchema],
) -> Result<String, Error> {
    let mut types = types.clone();
    let wire = crate::wire::WireTypes::new(&mut types);
    let mut commands = commands.to_vec();
    for command in &mut commands {
        for (_, ty) in &mut command.function.args {
            wire.normalize(ty);
        }
        if let Some(ty) = &mut command.function.result {
            wire.normalize(ty);
        }
    }
    let mut events = events.to_vec();
    for event in &mut events {
        wire.normalize(&mut event.datatype);
    }
    Exporter::from(Typescript::default())
        .framework_prelude("// Generated by tauri3-specta. Do not edit.\n")
        .framework_runtime(move |exporter| render(exporter, &commands, &events))
        .export(&types, PhasesFormat)
}

fn render(
    exporter: FrameworkExporter<'_>,
    commands: &[Command],
    events: &[EventSchema],
) -> Result<Cow<'static, str>, Error> {
    // These aliases are private to the generated module. User types may use
    // ordinary names such as Channel, Event, or commands without colliding.
    for datatype in exporter.types.into_unsorted_iter() {
        if datatype.name.starts_with("__t3") || datatype.name == "CommandErrors" {
            return Err(Error::framework(
                "",
                format!("reserved generated name: {}", datatype.name),
            ));
        }
    }
    let mut source = String::from(
        "import { invoke as __t3Invoke, Channel as __t3Channel } from '@tauri-apps/api/core';\n",
    );
    if !events.is_empty() {
        source.push_str("import { listen as __t3Listen, once as __t3Once, emit as __t3Emit, emitTo as __t3EmitTo, type EventCallback as __t3Callback, type EventTarget as __t3Target } from '@tauri-apps/api/event';\n");
    }
    source.push_str("\nexport const commands = {\n");
    let mut errors = String::from(
        "\n/** Declared Rust errors. IPC/transport failures remain unknown. */\nexport type CommandErrors = {\n",
    );
    for command in commands {
        let mut argument_names = BTreeSet::new();
        let arguments = command
            .function
            .args
            .iter()
            .map(|(name, datatype)| {
                let name = if command.snake_case {
                    name.to_snake_case()
                } else {
                    name.to_lower_camel_case()
                };
                if !argument_names.insert(name.clone()) {
                    return Err(Error::framework(
                        "",
                        format!("{}: duplicate argument after casing: {name}", command.name),
                    ));
                }
                Ok(format!(
                    "{}: {}",
                    literal(&name),
                    render_argument(datatype, &exporter)?
                ))
            })
            .collect::<Result<Vec<_>, Error>>()?;
        let (success, error) = match &command.function.result {
            None => ("null".to_owned(), "never".to_owned()),
            Some(datatype) => match standard_generics(
                datatype,
                exporter.types,
                "Result",
                &["std::result", "core::result"],
            ) {
                Some(generics) => {
                    let [(_, success), (_, error)] = generics else {
                        return Err(Error::framework("", "unexpected Specta Result metadata"));
                    };
                    (
                        render_type(success, Phase::Serialize, &exporter)?,
                        render_type(error, Phase::Serialize, &exporter)?,
                    )
                }
                None => (
                    render_type(datatype, Phase::Serialize, &exporter)?,
                    "never".to_owned(),
                ),
            },
        };
        let key = literal(&command.name.to_lower_camel_case());
        if arguments.is_empty() {
            writeln!(
                source,
                "  {key}: (): Promise<{success}> => __t3Invoke<{success}>({}),",
                literal(&command.name)
            )
            .expect("write to String");
        } else {
            writeln!(
                source,
                "  {key}: (args: {{ {} }}): Promise<{success}> => __t3Invoke<{success}>({}, args),",
                arguments.join("; "),
                literal(&command.name)
            )
            .expect("write to String");
        }
        writeln!(errors, "  {key}: {error};").expect("write to String");
    }
    source.push_str("} as const;\n");
    errors.push_str("};\n");
    source.push_str(&errors);
    if !events.is_empty() {
        source.push_str("\nexport const events = {\n");
        for event in events {
            let name = literal(event.name);
            let key = if event.name == "__proto__" {
                format!("[{name}]")
            } else {
                name.clone()
            };
            let received = render_type(&event.datatype, Phase::Serialize, &exporter)?;
            let sent = render_type(&event.datatype, Phase::Deserialize, &exporter)?;
            writeln!(source, "  {key}: {{\n    name: {name},\n    listen: (handler: __t3Callback<{received}>) => __t3Listen<{received}>({name}, handler),\n    once: (handler: __t3Callback<{received}>) => __t3Once<{received}>({name}, handler),\n    emit: (payload: {sent}) => __t3Emit({name}, payload),\n    emitTo: (target: string | __t3Target, payload: {sent}) => __t3EmitTo(target, {name}, payload),\n  }},").expect("write to String");
        }
        source.push_str("} as const;\n");
    }
    Ok(Cow::Owned(source))
}

fn literal(value: &str) -> String {
    serde_json::to_string(value).expect("a string is JSON serializable")
}

fn standard_generics<'a>(
    datatype: &'a DataType,
    types: &Types,
    name: &str,
    modules: &[&str],
) -> Option<&'a [(specta::datatype::Generic, DataType)]> {
    let DataType::Reference(Reference::Named(reference)) = datatype else {
        return None;
    };
    let definition = types
        .get(reference)
        .expect("collected type reference must resolve");
    if definition.name != name || !modules.contains(&definition.module_path.as_ref()) {
        return None;
    }
    match &reference.inner {
        NamedReferenceType::Reference { generics, .. } => Some(generics),
        _ => None,
    }
}

fn render_argument(datatype: &DataType, exporter: &FrameworkExporter<'_>) -> Result<String, Error> {
    if let Some(generics) = standard_generics(
        datatype,
        exporter.types,
        "TAURI_CHANNEL",
        &["tauri::ipc::channel"],
    ) {
        let [(_, payload)] = generics else {
            return Err(Error::framework("", "unexpected Tauri Channel metadata"));
        };
        return Ok(format!(
            "__t3Channel<{}>",
            render_type(payload, Phase::Serialize, exporter)?
        ));
    }
    render_type(datatype, Phase::Deserialize, exporter)
}

fn render_type(
    datatype: &DataType,
    phase: Phase,
    exporter: &FrameworkExporter<'_>,
) -> Result<String, Error> {
    let datatype = select_phase_datatype(datatype, exporter.types, phase);
    match &datatype {
        DataType::Reference(reference) => {
            primitives::reference(exporter.as_ref(), exporter.types, reference)
        }
        _ => primitives::inline(exporter.as_ref(), exporter.types, &datatype),
    }
}
